version: '3.7'
services:
    vjing-api-test:
        container_name: vjing-api-test
        image: 'aimeow/vjing-api-test:${BUILD_VERSION}'
        restart: always
        networks:
            - traefik-public
        labels:
            - 'traefik.enable=true'
            - 'traefik.tcp.routers.vjing-api-test.entrypoints=websecure'
            - 'traefik.http.routers.vjing-api-test.rule=Host(`vjing-api-test.aimeow.com`)'
            - 'traefik.http.routers.vjing-api-test.entrypoints=websecure'
            - 'traefik.http.routers.vjing-api-test.tls.certresolver=letsencryptresolver'
            - 'traefik.http.routers.vjing-api-test.service=vjing-api-test'
            - 'traefik.http.services.vjing-api-test.loadbalancer.server.port=3001'

    postgres:
        image: postgres:12
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
        name: nest-db

networks:
    traefik-public:
        external: true
