version: '3.7'
services:
    vjing-api-test:
        container_name: vjing-api-test
        image: 'aimeow/vjing-api-test:0.0.${BUILD_VERSION}'
        restart: always
        env_file:
            - .env
        labels:
            - 'traefik.enable=true'
            - 'traefik.tcp.routers.vjing-api-test.entrypoints=websecure'
            - 'traefik.http.routers.vjing-api-test.rule=Host(`vjing-api-test.aimeow.com`)'
            - 'traefik.http.routers.vjing-api-test.entrypoints=websecure'
            - 'traefik.http.routers.vjing-api-test.tls.certresolver=letsencryptresolver'
            - 'traefik.http.routers.vjing-api-test.service=vjing-api-test'
            - 'traefik.http.services.vjing-api-test.loadbalancer.server.port=3000'
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - traefik-public

    postgres:
        image: postgres:12
        container_name: postgres
        restart: always
        ports:
            - 15505:5432
        env_file:
            - .env
        volumes:
            - postgres:/var/lib/postgresql/data
        network_mode: 'host'

volumes:
    postgres:
        name: nest-db

networks:
    traefik-public:
        external: true
