name: Docker Image CI

on:
    push:
        branches: [develop, releases/**, master]
    pull_request:
        branches: [develop, releases/**, master]

jobs:
    build:
        if: ${{ github.ref == 'refs/heads/develop' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Print develop Branchg $GITHUB_REF"
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag vjing-api-test:$GITHUB_RUN_NUMBER

        if: ${{ github.ref == 'refs/heads/master' }}
        runs-on: ubuntu-latestg
        steps:
            - uses: actions/checkout@v2
            - run: echo "Print master Branchg $GITHUB_REF"
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag vjing-api:$GITHUB_RUN_NUMBER