name: Docker Image CI

on:
    push:
        branches: [develop, releases/**, master]
    pull_request:
        branches: [develop, releases/**, master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - run: echo "Print develop Branchg $GITHUB_REF"
              if: ${{ github.ref == 'refs/heads/develop' }}

            - run: echo "Print production Branchg $GITHUB_REF"
              if: ${{ github.ref == 'refs/heads/master' }}

            - name: Build the Developer Docker image
              run: docker build . --file Dockerfile --tag vjing-api-test:$GITHUB_RUN_NUMBER
              if: ${{ github.ref == 'refs/heads/develop' }}

            - name: Build the Production Docker image
              run: docker build . --file Dockerfile --tag vjing-api:$GITHUB_RUN_NUMBER
              if: ${{ github.ref == 'refs/heads/master' }}
