name: Docker Image CI

on:
    push:
        branches: [develop, releases/**]
    pull_request:
        branches: [develop, releases/**]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Print Branch $GITHUB_REF"
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag vjing-api:$(date +%s)
