name: Docker Image CI

on:
    push:
        branches: [develop, releases/**, master]
    pull_request:
        branches: [develop, releases/**, master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - run: echo "Print develop Branch $GITHUB_REF"
              if: ${{ github.ref == 'refs/heads/develop' }}

            - run: echo "Print production Branch $GITHUB_REF"
              if: ${{ github.ref == 'refs/heads/master' }}

            - name: Build the Developer Docker image
              run: docker build . --file Dockerfile --tag vjing-api-test:0.${{$GITHUB_RUN_NUMBER/10}}.${{$GITHUB_RUN_NUMBER%10}}
              if: ${{ github.ref == 'refs/heads/develop' }}

            - name: Build the Production Docker image
              run: docker build . --file Dockerfile --tag vjing-api:0.${{$GITHUB_RUN_NUMBER/10}}.${{$GITHUB_RUN_NUMBER%10}}
              if: ${{ github.ref == 'refs/heads/master' }}
